import { defineConfig } from '@unocss/vite';
import presetUno from '@unocss/preset-uno';
import transformerDirectives from '@unocss/transformer-directives';

export default defineConfig({
  content: {
    pipeline: {
      exclude: ['node_modules', 'dist', '.git', '.husky', '.vscode', 'public', 'build', './stats.html'],
    },
  },
  presets: [presetUno()],
  transformers: [transformerDirectives()],
  shortcuts: {
    'wh-full': 'w-full h-full',
    'flex-center': 'flex justify-center items-center',
    'flex-col-center': 'flex-center flex-col',
    'flex-x-center': 'flex justify-center',
    'flex-y-center': 'flex items-center',
    'i-flex-center': 'inline-flex justify-center items-center',
    'i-flex-x-center': 'inline-flex justify-center',
    'i-flex-y-center': 'inline-flex items-center',
    'flex-col': 'flex flex-col',
    'flex-col-stretch': 'flex-col items-stretch',
    'i-flex-col': 'inline-flex flex-col',
    'i-flex-col-stretch': 'i-flex-col items-stretch',
    'flex-1-hidden': 'flex-1 overflow-hidden',
    'absolute-lt': 'absolute left-0 top-0',
    'absolute-lb': 'absolute left-0 bottom-0',
    'absolute-rt': 'absolute right-0 top-0',
    'absolute-rb': 'absolute right-0 bottom-0',
    'absolute-tl': 'absolute-lt',
    'absolute-tr': 'absolute-rt',
    'absolute-bl': 'absolute-lb',
    'absolute-br': 'absolute-rb',
    'absolute-center': 'absolute-lt flex-center wh-full',
    'fixed-lt': 'fixed left-0 top-0',
    'fixed-lb': 'fixed left-0 bottom-0',
    'fixed-rt': 'fixed right-0 top-0',
    'fixed-rb': 'fixed right-0 bottom-0',
    'fixed-tl': 'fixed-lt',
    'fixed-tr': 'fixed-rt',
    'fixed-bl': 'fixed-lb',
    'fixed-br': 'fixed-rb',
    'fixed-center': 'fixed-lt flex-center wh-full',
    'nowrap-hidden': 'whitespace-nowrap overflow-hidden',
    'ellipsis-text': 'nowrap-hidden text-ellipsis',
    'transition-base': 'transition-all duration-300 ease-in-out',
  },
  rules: [
    [/^m-(\d+)$/, ([, d]) => ({ margin: `${d}px` })],
    [/^mx-(\d+)$/, ([, d]) => [{ 'margin-left': `${d}px` }, { 'margin-right': `${d}px` }]],
    [/^my-(\d+)$/, ([, d]) => [{ 'margin-top': `${d}px` }, { 'margin-bottom': `${d}px` }]],
    [/^mt-(\d+)$/, ([, d]) => ({ 'margin-top': `${d}px` })],
    [/^mb-(\d+)$/, ([, d]) => ({ 'margin-bottom': `${d}px` })],
    [/^ml-(\d+)$/, ([, d]) => ({ 'margin-left': `${d}px` })],
    [/^mr-(\d+)$/, ([, d]) => ({ 'margin-right': `${d}px` })],
    [/^-mt-(\d+)$/, ([, d]) => ({ 'margin-top': `-${d}px` })],
    [/^-mb-(\d+)$/, ([, d]) => ({ 'margin-bottom': `-${d}px` })],
    [/^-ml-(\d+)$/, ([, d]) => ({ 'margin-left': `-${d}px` })],
    [/^-mr-(\d+)$/, ([, d]) => ({ 'margin-right': `-${d}px` })],
    [/^p-(\d+)$/, ([, d]) => ({ padding: `${d}px` })],
    [/^px-(\d+)$/, ([, d]) => [{ 'padding-left': `${d}px` }, { 'padding-right': `${d}px` }]],
    [/^py-(\d+)$/, ([, d]) => [{ 'padding-top': `${d}px` }, { 'padding-bottom': `${d}px` }]],
    [/^pt-(\d+)$/, ([, d]) => ({ 'padding-top': `${d}px` })],
    [/^pb-(\d+)$/, ([, d]) => ({ 'padding-bottom': `${d}px` })],
    [/^pl-(\d+)$/, ([, d]) => ({ 'padding-left': `${d}px` })],
    [/^pr-(\d+)$/, ([, d]) => ({ 'padding-right': `${d}px` })],
    [/^w-(\d+)$/, ([, d]) => ({ width: `${d}px` })],
    [/^h-(\d+)$/, ([, d]) => ({ height: `${d}px` })],
    [/^l-(\d+)$/, ([, d]) => ({ 'line-height': `${d}px` })],
    [/^text-(\d+)$/, ([, d]) => ({ 'font-size': `${d}px` })],
    [/^color-(\w+)$/, ([, d]) => ({ color: `#${d}` })],
    [/^border-(\d+)px-(\w+)$/, ([, d, w]) => ({ border: `${d}px solid #${w}` })],
    [/^border-top-(\d+)px-(\w+)$/, ([, d, w]) => ({ 'border-top': `${d}px solid #${w}` })],
    [/^border-bottom-(\d+)px-(\w+)$/, ([, d, w]) => ({ 'border-bottom': `${d}px solid #${w}` })],
    [/^border-left-(\d+)px-(\w+)$/, ([, d, w]) => ({ 'border-left': `${d}px solid #${w}` })],
    [/^border-right-(\d+)px-(\w+)$/, ([, d, w]) => ({ 'border-right': `${d}px solid #${w}` })],
    [/^max-w-(\d+)$/, ([, d]) => ({ 'max-width': `${d}px` })],
    [/^max-h-(\d+)$/, ([, d]) => ({ 'max-height': `${d}px` })],
    [/^min-w-(\d+)$/, ([, d]) => ({ 'min-width': `${d}px` })],
    [/^min-h-(\d+)$/, ([, d]) => ({ 'min-height': `${d}px` })],
    [/^width-p-(\d+)$/, ([, d]) => ({ width: `${d}%` })],
    [/^br-(\d+)$/, ([, d]) => ({ 'border-radius': `${d}px` })],
    [/^bg-color-(\w+)$/, ([, d]) => ({ 'background-color': `#${d}` })],
    [/^letter-spacing-(\d+)$/, ([, d]) => ({ 'letter-spacing': `${d}px` })],
  ],
  theme: {
    colors: {
      dark: '#18181c',
    },
  },
});
